#!/bin/bash
BASE_IF=eth0

IP_A="172\.30\.1\..*\/24"
IP_B="172\.30\.2\..*\/24"
IP_C="172\.30\.3\..*\/24"
IP_D="172\.30\.4\..*\/24"
IP_T="10\.100\.2\..*\/24"

IP=`ip -4 addr show dev eth0`
ZONE=void

[[ $IP =~ $IP_A ]] && ZONE=`seq 101 115`
[[ $IP =~ $IP_B ]] && ZONE=`seq 201 212`
[[ $IP =~ $IP_C ]] && ZONE=`seq 301 306`
[[ $IP =~ $IP_D ]] && ZONE="2 3 4 5 15 20"
[[ $IP =~ $IP_T ]] && ZONE=`seq 101 115`

[[ $ZONE == void ]] && {
 echo /me is not in known network.
 exit
}

echo Creating VLAN Range $ZONE
modprobe 8021q

for i in $ZONE
do
  vconfig add $BASE_IF $i
done

sleep 3
