#!/bin/bash
# Dirty pull/compile/run loop.

WORKDIR=..
BINARY=b2m2b 

test  -z "$*"  && { 
	echo No parameter. No good.
	exit
}

pushd $WORKDIR

while ( true ) do
  ./$BINARY $*
  /bin/sleep 30
done

popd
