#!/bin/bash
MCAST="sit0"
NICS=/sys/class/net
IGNORE_NICS="lo sixxs ".$MCAST
UPDATE=1
WORKDIR=..

if [ $UPDATE == 1 ]
then
 echo Updating...
 pushd $WORKDIR
 git pull && make
 popd
fi

for x in $NICS/*
do
 NIC=${x/$NICS\//}
 [[ $IGNORE_NICS =~ $NIC ]]  || ./do_loop $MCAST $NIC &
done
