#!/bin/bash
# Dirty pull/compile/run loop.

UPDATE=1
WORKDIR=..
BINARY=b2m2b 

pushd $WORKDIR

while ( true ) do
  if [ $UPDATE == 1 ] 
  then
	echo Updating...
	git pull && make
  fi 

  ./$BINARY $*
  /bin/sleep 2
done

popd
