#!/bin/bash
MCAST="eth0"
NICS=/sys/class/net
IGNORE_NICS="lo sixxs sit0 wwan0 ".$MCAST
UPDATE=1
B_DIR=/opt/b2m2b

if [ $UPDATE == 1 ]
then
 echo Updating...
 pushd $B_DIR
 git pull && make
 popd
fi

for x in $NICS/*
do
 NIC=${x/$NICS\//}
 [[ $IGNORE_NICS =~ $NIC ]]  || ./do_loop $MCAST $NIC &
done
